mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('invidiouslinks/', include('invidiouslinks.urls')),
    path("trbotinput/", include("trbotinput.urls")),
    path("yturlfetch/", include("yturlfetch.urls")),
    path('admin/', admin.site.urls),
]

mysite/trbotinput/urls.py
from django.urls import path

from . import views

app_name = "trbotinput"
urlpatterns = [
    path("", views.IndexView, name="index"),
    path("<int:exercise_id>/", views.ExerciseView, name="exercise"),
]

mysite/trbotinput/models.py
from django.db import models

class Exercise(models.Model):
    exercise_id = models.PositiveIntegerField(primary_key=True, default=0)
    exercise_name = models.CharField(max_length=256)
    gif_name = models.CharField(max_length=256)
    correct_value = models.CharField(max_length=4096, default="")

    def __str__(self):
        return self.exercise_name + ": " + str(self.exercise_id)

class ExerciseStats(models.Model):
    exercise = models.OneToOneField(Exercise, on_delete=models.CASCADE, related_name="stats")
    total_answers = models.PositiveIntegerField(default=0)
    correct_answers = models.PositiveIntegerField(default=0)


ExerciseStats.short_description = "Exercise Stats"

mysite/trbotinput/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.db.models import F, Min

from .models import Exercise

def IndexView(request):

    minID = -1

    # Find the first entry available
    try:
        first_entry = Exercise.objects.all().aggregate(min_id=Min("exercise_id"))
        minID = first_entry.get("min_id")
    except:
        minID = -1
    
    if minID < 0:
        # print("minID < 0")
        return render(request, "trbotinput/index.html")

    # print("minID is OKAY!")
    return render(request, "trbotinput/index.html", { "first_entry": minID })

def ExerciseView(request, exercise_id):
    exercise = get_object_or_404(Exercise, pk=exercise_id)

    # print("EXERCISE ID: " + str(exercise.exercise_id))

    next_entry = -1
    last_entry = True
    correct_input = False
    input_text = None
    error_message = None

    try:
        idsGreaterThan = Exercise.objects.filter(exercise_id__gt=exercise_id)
        last_entry = idsGreaterThan.count() == 0
        
        if last_entry == False:
            next_entry = idsGreaterThan.order_by("exercise_id")[0].exercise_id
    except:
        last_entry = True

    if request.method == 'POST':
        input_text = request.POST["input"]

        if len(input_text) > 0:
        
            stats = exercise.stats

            stats.total_answers = F('total_answers') + 1

            if input_text == exercise.correct_value:
                correct_input = True
                stats.correct_answers = F('correct_answers') + 1
            else:
                error_message = "Incorrect input."

            stats.save()

            # Refresh from the database to get the correct values
            stats.refresh_from_db()
        else:
            input_text = None
            error_message = "No input provided."

    # print("next_entry: " + str(next_entry) + " | last_entry: " + str(last_entry) + " | correct_input: " + str(correct_input))

    return render(request, "trbotinput/exercise.html",
        { 
            "exercise": exercise,
            "last_entry": last_entry,
            "next_entry": next_entry,
            "correct_input": correct_input,
            "input_text": input_text,
            "error_message": error_message
        }
    )

mysite/trbotinput/templates/trbotinput/exercise.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'trbotinput/exercisestyle.css' %}">

<h1 class="header">{{ exercise.exercise_name }}</h1>

<body class="bodycontainer">
    <div class="container">
        <p>Total Answers - {{ exercise.stats.total_answers }} | Correct Answers: {{ exercise.stats.correct_answers }}</p>
        
        {# GIF #}
        <img src="{% static 'trbotinput/gifs/' %}{{ exercise.gif_name }}"></img>

        {# Instructions #}
        <p>Enter your input below. No exercises require specifying input durations.</p>

        {# Input Form #}
        <form action="{% url 'trbotinput:exercise' exercise.exercise_id %}" method="POST">
            {% csrf_token %}
            <div id="enterinput">
                <input type="text" id="entertext" name="input" placeholder="Enter your input here"></textarea> 
            </div>

            {# Submit Button #}
            <div class="submitinput">
                <input type="submit" value="Submit">
            </div>
        </form>  

        {# Display Input #}
        {% if input_text is not None %}
            <p>Your input was: "{{ input_text }}"</p>

            {# Next Button #}
            {% if next_entry >= 0 and correct_input == True %}
                <p>That's correct!</p>

                <form action="{% url 'trbotinput:exercise' next_entry %}" method="GET">
                    <button type="submit" value="Next!">Next Exercise</button>
                </form>
            {% else %}
                {% if last_entry == True %}
                    <p>Congratulations! You've completed all available exercises!</p>
                {% endif %}
            {% endif %}
        {% endif %}

        {% if error_message %}
            <p class="errorMsg">{{ error_message }}</p>
        {% endif %}
    </div>
</body>

mysite/trbotinput/templates/trbotinput/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'trbotinput/indexstyle.css' %}">

<h1 class="header">Welcome to TRBot's input exercises!</h1>

<body class="bodycontainer">
    <div class="container">
        <h2 class="header">Here's the rundown:</h2>
            <ol class="list">
                <li>Watch the GIF.</li>
                <li>Type your input into the text box.</li>
                <li>Submit your input and see your results! If you're close enough, you can move onto the next GIF.</li>
            </ol>
        <h3 class="header">Ready to start?</h3>
        
        {% if first_entry >= 0 %}
            <form action="{% url 'trbotinput:exercise' first_entry %}" method="GET">
                <button type="submit" value="Start">Start</button>
            </form>
        {% else %}
            <p class="errorMsg">No exercise ID found.</p>
        {% endif %}
    </div>
</body>