mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('invidiouslinks/', include('invidiouslinks.urls')),
    path("trbotinput/", include("trbotinput.urls")),
    path("yturlfetch/", include("yturlfetch.urls")),
    path('admin/', admin.site.urls),
]

mysite/yturlfetch/urls.py
from django.urls import path

from . import views

app_name = "yturlfetch"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<str:video_id>/", views.VideoView, name="video"),
]

mysite/yturlfetch/models.py
from django.db import models

class Video(models.Model):
    video_id = models.CharField(max_length=200, primary_key=True)

mysite/yturlfetch/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.db.models import F, Min

from .models import Video

class IndexView(generic.ListView):
    template_name = 'yturlfetch/index.html'
    
    context_object_name = 'video_list'

    def get_queryset(self):
        return Video.objects.all()

def VideoView(request, video_id):
    video = get_object_or_404(Video, pk=video_id)
    
    # https://invidio.us/api/v1/videos/video_id gets the video

    """
    <div id="player">
      <div id="player-wrap">
        ytplayer.config
          "args"
             "player_response"
               "streaming_data"
                 "formats" (array)
                   "url" (first array index)
    """

    # r = request.GET['player']['player-wrap'
    # print(r)

    return render(request, 'yturlfetch/video.html',
        { 
            'video': video,
        }
    )

mysite/yturlfetch/templates/yturlfetch/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'yturlfetch/indexstyle.css' %}">

<body id="bodycontainer">
<div id="container">
    {% if video_list %}
        <p>yturlfetch videos available:</p>
    {% for video in video_list %}
        <li><a href="{% url 'yturlfetch:video' video.video_id %}">{{ video.video_id }}</a></li>
    {% endfor %}
    {% else %}
        <p>Hello, you're at the yturlfetch index. No videos are available.</p>
    {% endif %}
</div>
</body>

mysite/yturlfetch/templates/yturlfetch/video.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'yturlfetch/videostyle.css' %}">

<body id="bodycontainer">
    <div id="container">
        <h3 id="h3container"><a href="{% url 'yturlfetch:index' %}">&larr; Back</a></h6>
        <h2 id="videoheader">Invidious ({{ video.video_id }})</h1>

        <div id="video">
            <iframe id='ivplayer' width='640' height='360' src='https://invidio.us/embed/{{ video.video_id }}' style='border:black;'></iframe>
        </div>

        <br>

        <h2 id="videoheader">Direct from Video</h2>
        <div id="video">
            {% comment %}<video></video>{% endcomment %}
        </div>
    </div>

</body>