mysite/invidiouslinks/urls.py
from django.urls import path

from . import views

app_name = 'invidiouslinks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:video_id>/', views.detail, name='detail')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('invidiouslinks/', include('invidiouslinks.urls')),
    path("trbotinput/", include("trbotinput.urls")),
    path("yturlfetch/", include("yturlfetch.urls")),
    path('admin/', admin.site.urls),
]

mysite/invidiouslinks/models.py
from django.db import models

class Video(models.Model):
    video_id = models.CharField(max_length=200, primary_key=True)
    video_name = models.CharField(max_length=100, default="VideoName")

    def __str__(self):
        return self.video_id + ": " + self.video_name

class Comment(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500)

    def __str__(self):
        return self.comment_text

mysite/invidiouslinks/forms.py
from django import forms

class CommentForm(forms.Form):
    comment_text = forms.CharField(label='Enter comment here...', max_length=500)

mysite/invidiouslinks/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.http import HttpResponse
from django.urls import reverse
from django.db.models import F
from django import forms

from .models import Video, Comment
from .forms import CommentForm

class IndexView(generic.ListView):
    template_name = 'invidiouslinks/index.html'
    
    context_object_name = 'video_list'

    def get_queryset(self):
        return Video.objects.all()

def detail(request, video_id):
    video = get_object_or_404(Video, pk=video_id)

    # print("Request method:" + str(request.method))

    if request.method == 'POST':
        # "comment" is the name of the input field holding the text
        comment_text = request.POST.get("comment", None)

        if (comment_text is None or len(comment_text) <= 2):
            return render(request, 'invidiouslinks/detail.html', { 'video': video, 'error_message': 'Comment text is too short' })

        try:
            selected_comment = video.comment_set.create(video=video, comment_text=comment_text)
            selected_comment.save()
        except (KeyError, Video.DoesNotExist):
            return render(request, 'invidiouslinks/detail.html', { 'video': video, 'error_message': 'Invalid video ID' })

    return render(request, 'invidiouslinks/detail.html',
        { 'video': video,
        }
    )

def index(request):
    return render(request, 'invidiouslinks/index.html')

# def addcomment(request, video_id):
#     video = get_object_or_404(Video, pk=video_id)
# 
#     if request.method == 'POST':
#         # "comment" is the name of the input
#         comment_text = request.POST.get("comment", None)
# 
#         if (len(comment_text) > 0):
#             return HttpResponseRedirect(reverse("invidiouslinks:detail"), { 'video': video, 'error_message': 'Comment text is empty' })
# 
#         try:
#             selected_comment = video.comment_set.create(video=video, comment_text=comment_text)
#             selected_comment.save()
#         except (KeyError, Video.DoesNotExist):
#             return render(request, 'invidiouslinks/detail.html', { 'video': video, 'error_message': 'Invalid video ID' })
# 
#     return HttpResponseRedirect(reverse("invidiouslinks:detail", args=(video_id)))

        # # if this is a POST request we need to process the form data
    # if request.method == 'POST':
    #     # create a form instance and populate it with data from the request:
    #     form = CommentForm(request.POST)
    #     # check whether it's valid:
    #     if form.is_valid():
    #         # process the data in form.cleaned_data as required
    #         # ...
    #         # redirect to a new URL:
    #         return HttpResponseRedirect(reverse('invidiouslinks:detail', args=(video_id)))
    #         
    # # if a GET (or any other method) we'll create a blank form
    # else:
    #     form = CommentForm()
# 
    # return render(request, 'invidiouslinks/detail.html', { 'video': video, 'form': form })

mysite/invidiouslinks/templates/invidiouslinks/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'invidiouslinks/detailstyle.css' %}">

<body id="bodycontainer">
    <div id="container">
        <h3 id="h3container"><a href="{% url 'invidiouslinks:index' %}">&larr; Back</a></h6>
        <h1 id="videoheader">{{ video.video_name }}</h1>

        <div id="video">
            <iframe id='ivplayer' width='640' height='360' src='https://invidio.us/embed/{{ video.video_id }}' style='border:black;'></iframe>
        </div>

        <br>

        {% if error_message %}
            <p class="error"><strong>{{ error_message }}</strong></p>
        {% endif %}

        <div id="commentbox">
            {# Since Comment has Video as a ForeignKey, "comment_set" is available - this is part of Django's template syntax #}
            
            <h3>Comments</h3>
            {% if video.comment_set and video.comment_set.all.count > 0 %}
                {% for comment in video.comment_set.all %}
                    <li>{{ comment.comment_text }}</li>
                {% endfor %}
            {% else %}
                <p>No comments available</p>
            {% endif %}
        </div>

        <div id="commentboxarea">

            {% comment %}
                Refresh this page with POST data.
                The "comment" textarea will be sent as the POST data.
                The name determines how to reference it. 
            {% endcomment %}
            <form action="{% url 'invidiouslinks:detail' video.video_id %}" method="POST">
                {% csrf_token %}  
                <div id="entertext">
                    <textarea id="entertext" name="comment" placeholder="Enter comment..."></textarea> 
                </div>

                <div id="submittext">
                    <input type="submit" value="Submit">
                </div>
            </form>  
        </div>
    </div>

</body>

mysite/invidiouslinks/templates/invidiouslinks/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'invidiouslinks/indexstyle.css' %}">

<body id="bodycontainer">
<div id="container">
    {% if video_list %}
        <p>invidiouslinks videos available:</p>
    {% for video in video_list %}
        <li><a href="{% url 'invidiouslinks:detail' video.video_id %}">{{ video.video_name }}</a></li>
    {% endfor %}
    {% else %}
        <p>Hello, you're at the invidiouslinks index. No videos are available.</p>
    {% endif %}
</div>
</body>